# Generated by Django 4.1 on 2022-09-01 10:05

import corepetimus.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PetimusType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100, verbose_name='Descipción del tipo de Petimus')),
            ],
        ),
        migrations.CreateModel(
            name='Petimus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Título Petimus')),
                ('description', models.CharField(max_length=500, verbose_name='Descipción del Petimus')),
                ('country', models.CharField(max_length=50, verbose_name='Pais')),
                ('administrative', models.CharField(max_length=100, verbose_name='Provincia / comunidad autonoma')),
                ('city', models.CharField(max_length=50, verbose_name='Ciudad')),
                ('address', models.CharField(max_length=100, verbose_name='Dirección')),
                ('zip_code', models.CharField(max_length=15, verbose_name='Código postal')),
                ('solvitur_date', models.DateTimeField(blank=True, null=True)),
                ('solvitur_description', models.CharField(blank=True, max_length=500, null=True)),
                ('status', models.CharField(choices=[('draft', 'Borrador'), ('published', 'Publicado')], default='published', max_length=10, verbose_name='Estado')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('update', models.DateTimeField(auto_now=True)),
                ('petimus_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='petimus_type', to='corepetimus.petimustype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='petimus', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=500)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('view', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_notification', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=corepetimus.models.user_directory_path)),
                ('url', models.URLField(blank=True)),
                ('description', models.CharField(blank=True, max_length=250, null=True)),
                ('solvitur', models.BooleanField(choices=[(False, 'No'), (True, 'Si')], default=False, max_length=3, verbose_name='Restuelto Si/No')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('update', models.DateTimeField(auto_now=True)),
                ('petimus_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='petimus_images', to='corepetimus.petimus')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=500)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('update', models.DateTimeField(auto_now=True)),
                ('petimus_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='petimus_comment', to='corepetimus.petimus')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_comment', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
