# Generated by Django 4.1 on 2022-09-01 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('corepetimus', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='url',
        ),
    ]
