# Generated by Django 4.1 on 2022-08-29 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('corepetimus', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='petimustype',
            old_name='descriprion',
            new_name='description',
        ),
    ]
