# Generated by Django 4.1 on 2022-09-01 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('corepetimus', '0002_remove_image_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='petimus_id',
            new_name='petimus',
        ),
        migrations.RenameField(
            model_name='image',
            old_name='petimus_id',
            new_name='petimus',
        ),
    ]
